# Versi API untuk objek Service
apiVersion: v1

# Jenis objek yang akan dibuat
kind: Service

# Metadata untuk objek Service, termasuk nama objeknya
metadata:
  name: mongo-service # Nama Service

# Spesifikasi untuk Service
spec:
  # Konfigurasi untuk port yang akan di-expose oleh Service
  ports:
    - protocol: TCP # Protokol yang digunakan
      port: 27017 # Port eksternal yang akan di-expose oleh Service
      targetPort: 27017 # Port internal pod yang akan menjadi target

  # Selektor untuk menentukan pod mana yang akan dilayani oleh Service
  selector:
    app: mongodb # Label yang digunakan untuk memilih pod

  # Jenis Service
  type: NodePort # Memungkinkan akses eksternal melalui port pada node