# Versi API untuk objek Deployment
apiVersion: apps/v1

# Jenis objek yang akan dibuat
kind: Deployment

# Metadata untuk objek Deployment, termasuk nama objeknya
metadata:
  name: karsajobs-deployment # Nama Deployment

# Spesifikasi untuk Deployment, termasuk konfigurasi jumlah replika
spec:
  replicas: 2 # Jumlah replika yang akan dibuat

  # Selektor untuk menentukan pod mana yang termasuk dalam Deployment
  selector:
    matchLabels:
      app: karsajobs # Label yang digunakan untuk memilih pod

  # Template untuk pod yang akan dibuat oleh Deployment
  template:
    metadata:
      labels:
        app: karsajobs # Label yang diberikan pada pod
    spec:
      # Kontainer yang akan berjalan dalam pod
      containers:
        - name: karsajobs # Nama kontainer

          # Gambar Docker yang akan digunakan untuk kontainer
          image: ghcr.io/aldamrtz/a433-microservices/karsajobs:latest

          # Port yang akan diteruskan dari kontainer ke pod
          ports:
            - containerPort: 8080 # Port yang diexpose oleh kontainer

          # Environment variables yang akan diatur dalam kontainer
          env:
            - name: APP_PORT
              value: "8080" # Nilai port aplikasi dalam kontainer
            - name: MONGO_HOST
              value: mongo-service # Nama layanan MongoDB yang akan digunakan
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME # Nama pengguna MongoDB dari secret
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD # Kata sandi MongoDB dari secret
