# .github/workflows/ci-karsajobs.yml
name: CI - Karsajobs

on:
  push:
    branches:
      - karsajobs
  pull_request:
    branches:
      - karsajobs

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.15

      # 3. Lint Dockerfile
      - name: Lint Dockerfile
        run: |
          sudo apt-get update
          sudo apt-get install -y hadolint
          hadolint karsajobs/Dockerfile

      # 4. Download Go modules
      - name: Go modules
        run: go mod download
        working-directory: ./karsajobs

      # 5. Run unit tests
      - name: Run backend tests
        run: go test -v -short --count=1 ./...
        working-directory: ./karsajobs

      # 6. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/a433-microservices/karsajobs:latest karsajobs

      # 7. Log in to GitHub Packages
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 8. Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/a433-microservices/karsajobs:latest
