name: CI for karsajobs

on:
  push:
    branches:
      - karsajobs

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install hadolint
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      - name: Lint Dockerfile
        run: hadolint karsajobs/Dockerfile

  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install Dependencies
        run: |
          cd karsajobs
          go mod download

      - name: Run Unit Tests
        run: |
          cd karsajobs
          go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build and Push Docker Image
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        run: |
          echo $GHCR_PAT | docker login ghcr.io -u aldamrtz --password-stdin
          docker build -t aldaaa/karsajobs:latest -f karsajobs/Dockerfile karsajobs
          docker tag aldaaa/karsajobs:latest ghcr.io/aldamrtz/a433-microservices/karsajobs:latest
          docker push ghcr.io/aldamrtz/a433-microservices/karsajobs:latest
