name: CI KarsaJobs Backend

on:
  push:
    branches: [ "karsajobs" ]
  pull_request:
    branches: [ "karsajobs" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Lint Dockerfile
        run: |
          sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint
          hadolint Dockerfile

      - name: Run unit test
        run: go test -v -short --count=1 $(go list ./...)

      - name: Build Docker image
        run: docker build -t karsajobs:latest .
